LIB_SGP4_VERSION = 0.1

STATIC_TARGET := libsgp4.a
SHARED_TARGET := libsgp4.so.$(LIB_SGP4_VERSION)

BUILD_DIR ?= $(CURDIR)

BUILD_DIR_ABS = $(abspath $(BUILD_DIR))

TOOLCHAIN_PREFIX ?= 
AR_FLAGS_APPEND ?= 
LD_FLAGS_APPEND ?= 
CC_FLAGS_APPEND ?= 

AR_FLAGS := rcs
LD_FLAGS := -shared -soname $(SHARED_TARGET) -lc -lm

AR_FLAGS += $(AR_FLAGS_APPEND)
LD_FLAGS += $(LD_FLAGS_APPEND)

AR := $(TOOLCHAIN_PREFIX)ar
LD := $(TOOLCHAIN_PREFIX)ld

.PHONY: all
all:
	@echo "Compiling libsgp4..."
	$(MAKE) -C src BUILD_DIR=$(BUILD_DIR_ABS) TOOLCHAIN_PREFIX=$(TOOLCHAIN_PREFIX) CC_FLAGS_APPEND="$(CC_FLAGS_APPEND)"
	$(AR) $(AR_FLAGS) $(BUILD_DIR_ABS)/$(STATIC_TARGET) $(BUILD_DIR_ABS)/*.o
	$(LD) $(LD_FLAGS) -o $(BUILD_DIR_ABS)/$(SHARED_TARGET) $(BUILD_DIR_ABS)/*.o

.PHONY: clean
clean:
	rm $(BUILD_DIR_ABS)/*.o $(BUILD_DIR_ABS)/*.a $(BUILD_DIR_ABS)/*.so*
